modLoader = "kotlinforforge"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "coin"
version = "1.1"
displayName = "Coin"
authors = "hwangseonu"
description = "동전을 추가하는 모드입니다."

[[dependencies.coin]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"
