default: 1000

messages:
  prefix: "[Economy]"

  givedmoney: "%issuer%가 당신에게 %amount%만큼의 돈을 지급했습니다."
  settedmoney: "%issuer%가 당신의 돈을 %amount%%unit%으로 세팅했습니다."
  takedmoney: "%issuer%가 당신에게서 %amount%%unit%만큼의 돈을 수거했습니다."

  commands:
    mymoney: "나의 돈: %amount%%unit%"
    seemoney: "%target%의 돈: %amount%%unit%"
    setmoney: "%target%의 돈을 %amount%%unit%으로 세팅했습니다."
    givemoney: "%target%에게 %amount%%unit%만큼의 돈을 지급했습니다."
    takemoney: "%target%에게서 %amount%%unit%만큼의 돈을 수거했습니다."

  errors:
    unknown: "예상치못한 오류가 발생하였습니다."
    onlyplayer: "플레이어만 사용가능한 기능입니다."
    noaccount: "계정 정보를 찾을 수 없습니다."
    notenough: "소지하고 있는 돈이 충분하지 않습니다."
    moneybelowzero: "0원 이하의 돈을 처리할 수 없습니다."

  cash:
    bankname: "중앙은행"
    certification: "고유번호: %uid%"
    published: "현금을 발급하였습니다. 금액: %money%%unit%"
