default: 1000

messages:
  prefix: "[Economy]"
  mymoney: "나의 돈: %money%%unit%"
  noaccount: "%player%님의 정보를 찾을 수 없습니다."
  onlyplayer: "플레이어만 사용가능한 기능입니다."
  notenough: "소지하고 계신 돈이 충분하지 않습니다. %amount%%unit%만큼 더 필요합니다."
  givemoney: "%target%에게 %amount%%unit%만큼의 돈을 지급했습니다."
  setmoney: "%target%의 돈을 %amount%%unit%으로 세팅했습니다."
  unknownerror: "예상치못한 오류가 발생하였습니다."

  cash:
    bankname: "중앙은행"
    certification: "고유번호: %uid%"
    published: "현금을 발급하였습니다. 금액: %money%%unit%"