name: EconomySystem
author: hwangseonu
version: 1.0-SNAPSHOT
main: me.mocha.economy.Economy
api-version: "1.16"

commands:
  mymoney:
    permission: economy.command.mymoney
    description: 자신의 돈을 확인합니다.
    usage: /mymoney
    aliases: ["내돈"]
  seemoney:
    permission: economy.command.seemoney
    description: 플레이어의 돈을 확인합니다.
    usage: /takemoney <player>
  cash:
    permission: economy.command.cash
    description: 자신의 돈을 현금화합니다.
    usage: /cash <amount>
    aliases: ["현금"]
  setmoney:
    permission: economy.command.setmoney
    description: 플레이어에게 돈을 설정합니다.
    usage: /setmoney <player> <amount>
  givemoney:
    permission: economy.command.givemoney
    description: 플레이어에게 돈을 줍니다.
    usage: /givemoney <player> <amount>
  takemoney:
    permission: economy.command.takemoney
    description: 플레이어의 돈을 수거합니다.
    usage: /takemoney <player> <amount>

permissions:
  economy:
    default: op
    description: Allows players to control economy system.
    children:
      economy.command:
        default: op
        description: Allows players to use economy command.
        children:
          economy.command.mymoney:
            default: true
            description: Allows players to see their money.
          economy.command.seemoney:
            default: op
            description: Allows player to see money of other player.
          economy.command.cash:
            default: true
            description: Allows players to make cash.
          economy.command.setmoney:
            default: op
            description: Allows players to set money of other player.
          economy.command.givemoney:
            default: op
            description: Allows players to give money of other player.
          economy.command.takemoney:
            default: op
            description: Allows players to take money of other player.
